2025-05-21 03:46:46,323 INFO    StreamThr :6451 [internal.py:wandb_internal():90] W&B internal server running at pid: 6451, started at: 2025-05-21 03:46:46.322199
2025-05-21 03:46:46,324 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: status
2025-05-21 03:46:46,325 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: status
2025-05-21 03:46:46,326 DEBUG   SenderThread:6451 [sender.py:send():302] send: header
2025-05-21 03:46:46,326 INFO    WriterThread:6451 [datastore.py:open_for_write():75] open: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/run-1l8khnmf.wandb
2025-05-21 03:46:46,335 DEBUG   SenderThread:6451 [sender.py:send():302] send: run
2025-05-21 03:46:47,424 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: check_version
2025-05-21 03:46:47,430 INFO    SenderThread:6451 [dir_watcher.py:__init__():216] watching files in: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files
2025-05-21 03:46:47,430 INFO    SenderThread:6451 [sender.py:_start_run_threads():913] run started: 1l8khnmf with start time 1747799206.318659
2025-05-21 03:46:47,430 DEBUG   SenderThread:6451 [sender.py:send():302] send: summary
2025-05-21 03:46:47,431 INFO    SenderThread:6451 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2025-05-21 03:46:47,431 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: check_version
2025-05-21 03:46:47,737 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: run_start
2025-05-21 03:46:47,776 DEBUG   HandlerThread:6451 [meta.py:__init__():35] meta init
2025-05-21 03:46:47,776 DEBUG   HandlerThread:6451 [meta.py:__init__():50] meta init done
2025-05-21 03:46:47,776 DEBUG   HandlerThread:6451 [meta.py:probe():216] probe
2025-05-21 03:46:47,790 DEBUG   HandlerThread:6451 [meta.py:_setup_git():206] setup git
2025-05-21 03:46:47,804 DEBUG   HandlerThread:6451 [meta.py:_setup_git():213] setup git done
2025-05-21 03:46:47,804 DEBUG   HandlerThread:6451 [meta.py:_save_pip():54] save pip
2025-05-21 03:46:47,805 DEBUG   HandlerThread:6451 [meta.py:_save_pip():68] save pip done
2025-05-21 03:46:47,805 DEBUG   HandlerThread:6451 [meta.py:_save_conda():75] save conda
2025-05-21 03:46:48,432 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_created():275] file/dir created: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/conda-environment.yaml
2025-05-21 03:46:48,432 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_created():275] file/dir created: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/requirements.txt
2025-05-21 03:46:48,432 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_created():275] file/dir created: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/wandb-summary.json
2025-05-21 03:46:49,047 DEBUG   HandlerThread:6451 [meta.py:_save_conda():85] save conda done
2025-05-21 03:46:49,047 DEBUG   HandlerThread:6451 [meta.py:probe():254] probe done
2025-05-21 03:46:49,099 DEBUG   SenderThread:6451 [sender.py:send():302] send: files
2025-05-21 03:46:49,099 INFO    SenderThread:6451 [sender.py:_save_file():1156] saving file wandb-metadata.json with policy now
2025-05-21 03:46:49,104 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: stop_status
2025-05-21 03:46:49,105 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: stop_status
2025-05-21 03:46:49,433 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/conda-environment.yaml
2025-05-21 03:46:49,433 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_created():275] file/dir created: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/wandb-metadata.json
2025-05-21 03:46:49,448 DEBUG   SenderThread:6451 [sender.py:send():302] send: telemetry
2025-05-21 03:46:49,601 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1875] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gszhao-cncnet/CIFAR10/1l8khnmf/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250521T034649Z&X-Goog-Expires=86399&X-Goog-Signature=87d11804ab2fa43c280b5756d3a2e286b0ae555d69dc20f8b5ab977cfcca7c59fb45a3be07810f85e22b0cb27fd69c028691ec647643020194b9e068754d1300096c7896173bcc4499911d223abe585bdf518f69e65186f01742260f32557143ff6c326a51c6c74db61f697394b8dd2c5915873a424aa0daffba4ca26f5e0fc6e51046db30bfcaaf7c058350bdc18944c7567415e9523a43039a850924b461dc25df4365afd806e7e4456a6a6ee5e9bbf552d0166301a324edfb7fef44db07a952495f2e202923106a43e258a8801860e1ad7e3e86c5b2069a91a47f388ccdace062d3b3845482d0f73f06717655473ba11a9b57d84e0816b46be4428e14fe6a&X-Goog-SignedHeaders=host&X-User=gszhao: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-21 03:46:49,601 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1877] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '777'}
2025-05-21 03:46:49,601 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1879] upload_file response body: 
2025-05-21 03:46:50,433 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_created():275] file/dir created: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/output.log
2025-05-21 03:46:51,074 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1875] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gszhao-cncnet/CIFAR10/1l8khnmf/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250521T034649Z&X-Goog-Expires=86399&X-Goog-Signature=87d11804ab2fa43c280b5756d3a2e286b0ae555d69dc20f8b5ab977cfcca7c59fb45a3be07810f85e22b0cb27fd69c028691ec647643020194b9e068754d1300096c7896173bcc4499911d223abe585bdf518f69e65186f01742260f32557143ff6c326a51c6c74db61f697394b8dd2c5915873a424aa0daffba4ca26f5e0fc6e51046db30bfcaaf7c058350bdc18944c7567415e9523a43039a850924b461dc25df4365afd806e7e4456a6a6ee5e9bbf552d0166301a324edfb7fef44db07a952495f2e202923106a43e258a8801860e1ad7e3e86c5b2069a91a47f388ccdace062d3b3845482d0f73f06717655473ba11a9b57d84e0816b46be4428e14fe6a&X-Goog-SignedHeaders=host&X-User=gszhao: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-21 03:46:51,074 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1877] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '777'}
2025-05-21 03:46:51,075 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1879] upload_file response body: 
2025-05-21 03:46:52,435 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/output.log
2025-05-21 03:46:53,539 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1875] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gszhao-cncnet/CIFAR10/1l8khnmf/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250521T034649Z&X-Goog-Expires=86399&X-Goog-Signature=87d11804ab2fa43c280b5756d3a2e286b0ae555d69dc20f8b5ab977cfcca7c59fb45a3be07810f85e22b0cb27fd69c028691ec647643020194b9e068754d1300096c7896173bcc4499911d223abe585bdf518f69e65186f01742260f32557143ff6c326a51c6c74db61f697394b8dd2c5915873a424aa0daffba4ca26f5e0fc6e51046db30bfcaaf7c058350bdc18944c7567415e9523a43039a850924b461dc25df4365afd806e7e4456a6a6ee5e9bbf552d0166301a324edfb7fef44db07a952495f2e202923106a43e258a8801860e1ad7e3e86c5b2069a91a47f388ccdace062d3b3845482d0f73f06717655473ba11a9b57d84e0816b46be4428e14fe6a&X-Goog-SignedHeaders=host&X-User=gszhao: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-21 03:46:53,539 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1877] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '777'}
2025-05-21 03:46:53,539 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1879] upload_file response body: 
2025-05-21 03:46:53,539 ERROR   Thread-16 :6451 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/FedFed/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/FedFed/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/FedFed/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1872, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1888, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1872, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/FedFed/lib/python3.8/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-05-21 03:46:54,437 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/output.log
2025-05-21 03:46:57,812 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1875] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gszhao-cncnet/CIFAR10/1l8khnmf/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250521T034649Z&X-Goog-Expires=86399&X-Goog-Signature=87d11804ab2fa43c280b5756d3a2e286b0ae555d69dc20f8b5ab977cfcca7c59fb45a3be07810f85e22b0cb27fd69c028691ec647643020194b9e068754d1300096c7896173bcc4499911d223abe585bdf518f69e65186f01742260f32557143ff6c326a51c6c74db61f697394b8dd2c5915873a424aa0daffba4ca26f5e0fc6e51046db30bfcaaf7c058350bdc18944c7567415e9523a43039a850924b461dc25df4365afd806e7e4456a6a6ee5e9bbf552d0166301a324edfb7fef44db07a952495f2e202923106a43e258a8801860e1ad7e3e86c5b2069a91a47f388ccdace062d3b3845482d0f73f06717655473ba11a9b57d84e0816b46be4428e14fe6a&X-Goog-SignedHeaders=host&X-User=gszhao: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-21 03:46:57,813 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1877] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '777'}
2025-05-21 03:46:57,813 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1879] upload_file response body: 
2025-05-21 03:46:58,439 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/output.log
2025-05-21 03:47:04,451 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: stop_status
2025-05-21 03:47:04,451 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: stop_status
2025-05-21 03:47:06,608 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1875] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/gszhao-cncnet/CIFAR10/1l8khnmf/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250521%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250521T034649Z&X-Goog-Expires=86399&X-Goog-Signature=87d11804ab2fa43c280b5756d3a2e286b0ae555d69dc20f8b5ab977cfcca7c59fb45a3be07810f85e22b0cb27fd69c028691ec647643020194b9e068754d1300096c7896173bcc4499911d223abe585bdf518f69e65186f01742260f32557143ff6c326a51c6c74db61f697394b8dd2c5915873a424aa0daffba4ca26f5e0fc6e51046db30bfcaaf7c058350bdc18944c7567415e9523a43039a850924b461dc25df4365afd806e7e4456a6a6ee5e9bbf552d0166301a324edfb7fef44db07a952495f2e202923106a43e258a8801860e1ad7e3e86c5b2069a91a47f388ccdace062d3b3845482d0f73f06717655473ba11a9b57d84e0816b46be4428e14fe6a&X-Goog-SignedHeaders=host&X-User=gszhao: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2025-05-21 03:47:06,609 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1877] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '777'}
2025-05-21 03:47:06,609 ERROR   Thread-16 :6451 [internal_api.py:upload_file():1879] upload_file response body: 
2025-05-21 03:47:09,810 DEBUG   SenderThread:6451 [sender.py:send():302] send: exit
2025-05-21 03:47:09,810 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: poll_exit
2025-05-21 03:47:09,812 INFO    SenderThread:6451 [sender.py:send_exit():438] handling exit code: 255
2025-05-21 03:47:09,812 INFO    SenderThread:6451 [sender.py:send_exit():440] handling runtime: 22
2025-05-21 03:47:09,814 INFO    SenderThread:6451 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2025-05-21 03:47:09,814 INFO    SenderThread:6451 [sender.py:send_exit():446] send defer
2025-05-21 03:47:09,814 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: poll_exit
2025-05-21 03:47:09,814 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:09,814 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 0
2025-05-21 03:47:09,815 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:09,815 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 0
2025-05-21 03:47:09,815 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 1
2025-05-21 03:47:09,815 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:09,815 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 1
2025-05-21 03:47:09,918 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: poll_exit
2025-05-21 03:47:09,918 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:09,918 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 1
2025-05-21 03:47:09,918 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 2
2025-05-21 03:47:09,919 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: poll_exit
2025-05-21 03:47:09,919 DEBUG   SenderThread:6451 [sender.py:send():302] send: stats
2025-05-21 03:47:09,920 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:09,920 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 2
2025-05-21 03:47:09,920 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:09,920 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 2
2025-05-21 03:47:09,920 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 3
2025-05-21 03:47:09,921 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:09,921 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 3
2025-05-21 03:47:09,921 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:09,921 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 3
2025-05-21 03:47:09,921 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 4
2025-05-21 03:47:09,921 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:09,921 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 4
2025-05-21 03:47:09,921 DEBUG   SenderThread:6451 [sender.py:send():302] send: summary
2025-05-21 03:47:09,922 INFO    SenderThread:6451 [sender.py:_save_file():1156] saving file wandb-summary.json with policy end
2025-05-21 03:47:09,922 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:09,922 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 4
2025-05-21 03:47:09,922 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 5
2025-05-21 03:47:09,923 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:09,923 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 5
2025-05-21 03:47:09,923 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:09,923 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 5
2025-05-21 03:47:10,021 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: poll_exit
2025-05-21 03:47:10,308 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 6
2025-05-21 03:47:10,308 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: poll_exit
2025-05-21 03:47:10,309 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:10,309 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 6
2025-05-21 03:47:10,309 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:10,309 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 6
2025-05-21 03:47:10,410 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: poll_exit
2025-05-21 03:47:10,444 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/config.yaml
2025-05-21 03:47:10,444 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/wandb-summary.json
2025-05-21 03:47:12,445 INFO    Thread-12 :6451 [dir_watcher.py:_on_file_modified():292] file/dir modified: /root/FedFed/wandb/run-20250521_034646-1l8khnmf/files/output.log
2025-05-21 03:47:13,492 INFO    SenderThread:6451 [sender.py:transition_state():459] send defer: 7
2025-05-21 03:47:13,492 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: poll_exit
2025-05-21 03:47:13,494 DEBUG   HandlerThread:6451 [handler.py:handle_request():141] handle_request: defer
2025-05-21 03:47:13,494 INFO    HandlerThread:6451 [handler.py:handle_request_defer():164] handle defer: 7
2025-05-21 03:47:13,494 DEBUG   SenderThread:6451 [sender.py:send_request():316] send_request: defer
2025-05-21 03:47:13,494 INFO    SenderThread:6451 [sender.py:send_request_defer():455] handle sender defer: 7
2025-05-21 03:47:13,495 INFO    SenderThread:6451 [dir_watcher.py:finish():362] shutting down directory watcher
2025-05-21 03:47:13,837 INFO    MainThread:6451 [internal.py:handle_exit():80] Internal process exited
2025-05-21 03:47:13,838 WARNING MsgRouterThr:6451 [router.py:message_loop():73] EOFError seen in message_loop
